export enum TEMPERATURE_UNIT {
  METRIC = 'm',
  SCIENTIFIC = 's',
  FAHRENHEIT = 'f'
}

export const WEATHER_TEMPERATURE_UNIT_DEFAULT: TEMPERATURE_UNIT = TEMPERATURE_UNIT.METRIC;

export const WEATHER_TEMPERATURE_UNIT: Map<TEMPERATURE_UNIT, string> = new Map([
  [TEMPERATURE_UNIT.METRIC, 'Metric'],
  [TEMPERATURE_UNIT.SCIENTIFIC, 'Scientific'],
  [TEMPERATURE_UNIT.FAHRENHEIT, 'Fahrenheit']
]);