export enum TEMPERATURE_UNIT {
  METRIC = 'm',
  SCIENTIFIC = 's',
  FAHRENHEIT = 'f'
}

export const WEATHER_TEMPERATURE_UNIT_DEFAULT: TEMPERATURE_UNIT = TEMPERATURE_UNIT.METRIC;

export const WEATHER_SYSTEM_UNIT_NAME: Map<TEMPERATURE_UNIT, string> = new Map([
  [TEMPERATURE_UNIT.METRIC, 'Metric'],
  [TEMPERATURE_UNIT.SCIENTIFIC, 'Scientific'],
  [TEMPERATURE_UNIT.FAHRENHEIT, 'Fahrenheit']
]);

export const WEATHER_TEMPERATURE_UNIT_CODE: Map<TEMPERATURE_UNIT, string> = new Map([
  [TEMPERATURE_UNIT.METRIC, '&#8451;'],
  [TEMPERATURE_UNIT.SCIENTIFIC, '&#8490;'],
  [TEMPERATURE_UNIT.FAHRENHEIT, '&#8457;']
]);

export const WEATHER_TEMPERATURE_UNIT_CODE_DEFAULT: string = '&#8451;';
